/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Outdoor Event Booking API
 * OpenAPI spec version: 1.0.0
 */
export type RegisterVendor409 = {
  code?: number;
  message?: string;
};

export type RegisterVendor201 = {
  code?: number;
  message?: string;
};

export type RegisterVendorBody = {
  email?: string;
  name?: string;
  password?: string;
};

export type RegisterUser409 = {
  code?: number;
  message?: string;
};

export type RegisterUser201 = {
  code?: number;
  message?: string;
};

export type RegisterUserBody = {
  email?: string;
  name?: string;
  password?: string;
};
