/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Outdoor Event Booking API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import { HttpResponse, delay, http } from 'msw';

export const getRegisterUserMock = () => ({
  code: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  message: faker.helpers.arrayElement([faker.word.sample(), undefined]),
});

export const getRegisterVendorMock = () => ({
  code: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  message: faker.helpers.arrayElement([faker.word.sample(), undefined]),
});

export const getOutdoorEventBookingAPIMock = () => [
  http.post('*/v1/api/register-user', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(getRegisterUserMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  }),
  http.post('*/v1/api/register-vendor', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(getRegisterVendorMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  }),
];
